/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;

import Projeto.MaquinaDeTuring;

/**
 *
 * @author alysson
 */
public class TuringMachineSimulator extends javax.swing.JFrame {
	MaquinaDeTuring mt;
	boolean end = false;
	int delay = 200;
	int passos = 0;

	Timer timer = new Timer(delay, new ActionListener() {

		@Override
		public void actionPerformed(ActionEvent e) {
			passos++;
			end = mt.step();
			atualizarFita(mt.getFita());
			
			jLblPassos.setText(Integer.toString(passos));
			jLblEstadoAtual.setText(mt.estadoAtual.getName());
			//jTAConsole.setText(jTAConsole.getText() + "\n" + mt.TransicaoAtual);
			if (end)
				JbtnResetActionPerformed(null);
		}
	});

	/**
	 * Creates new form TuringMachineSimulator
	 */
	public TuringMachineSimulator() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jScrollPane4 = new javax.swing.JScrollPane();
		jPanel5 = new javax.swing.JPanel();
		jLblFitaLeft = new javax.swing.JLabel();
		jLblFitaHead = new javax.swing.JLabel();
		jLblFitaRight = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		jTfPalavra = new javax.swing.JTextField();
		jBtnIniciar = new javax.swing.JButton();
		jBtnPasso = new javax.swing.JButton();
		jBtnAbrir = new javax.swing.JButton();
		JbtnReset = new javax.swing.JButton();
		jPanel6 = new javax.swing.JPanel();
		jSVelocidade = new javax.swing.JSlider();
		jCBVelMaxima = new javax.swing.JCheckBox();
		jPanel8 = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		jLblEstadoAtual = new javax.swing.JLabel();
		jPanel7 = new javax.swing.JPanel();
		jLblPassos = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTAConsole = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fita",
				javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

		jLblFitaLeft.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
		jLblFitaLeft.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLblFitaLeft.setText("010101010010101010010101010");

		jLblFitaHead.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
		jLblFitaHead.setText("#");
		jLblFitaHead.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLblFitaRight.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
		jLblFitaRight.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLblFitaRight.setText("010101010010101010010101010");

		jLabel5.setIcon(new javax.swing.ImageIcon("/home/alysson/Documentos/arrowRD.png")); // NOI18N

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup()
						.addComponent(jLblFitaLeft, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGap(1, 1, 1)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
								.addComponent(jLabel5).addComponent(jLblFitaHead))
						.addGap(1, 1, 1).addComponent(jLblFitaRight, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
				.addGroup(jPanel5Layout.createSequentialGroup()
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLblFitaHead, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jLblFitaRight))
								.addComponent(jLblFitaLeft))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel5)));

		jScrollPane4.setViewportView(jPanel5);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane4));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE));

		jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controles",
				javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

		jTfPalavra.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

		jBtnIniciar.setText("Iniciar");
		jBtnIniciar.setEnabled(false);
		jBtnIniciar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBtnIniciarActionPerformed(evt);
			}
		});

		jBtnPasso.setText("Passo");
		jBtnPasso.setEnabled(false);
		jBtnPasso.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBtnPassoActionPerformed(evt);
			}
		});

		jBtnAbrir.setText("Abrir");
		jBtnAbrir.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBtnAbrirActionPerformed(evt);
			}
		});

		JbtnReset.setText("Reset");
		JbtnReset.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				JbtnResetActionPerformed(evt);
			}
		});

		jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Speed"));

		jCBVelMaxima.setText("Full Speed");

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						jPanel6Layout.createSequentialGroup().addComponent(jCBVelMaxima).addGap(0, 21, Short.MAX_VALUE))
				.addGroup(jPanel6Layout.createSequentialGroup()
						.addComponent(jSVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
						.addContainerGap()));
		jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel6Layout.createSequentialGroup().addContainerGap()
						.addComponent(jSVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
						.addComponent(jCBVelMaxima)));

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap()
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel4Layout.createSequentialGroup().addGroup(jPanel4Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(jBtnIniciar, javax.swing.GroupLayout.DEFAULT_SIZE,
														83, Short.MAX_VALUE)
												.addComponent(jBtnAbrir, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addGroup(jPanel4Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(JbtnReset, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jBtnPasso, javax.swing.GroupLayout.DEFAULT_SIZE,
																81, Short.MAX_VALUE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(jTfPalavra))));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup()
						.addComponent(jTfPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(jPanel4Layout.createSequentialGroup()
										.addGroup(jPanel4Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jBtnPasso).addComponent(jBtnIniciar))
										.addGap(18, 18, 18)
										.addGroup(jPanel4Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(JbtnReset).addComponent(jBtnAbrir)))
								.addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))));

		jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado atual",
				javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

		jLblEstadoAtual.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
		jLblEstadoAtual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLblEstadoAtual.setText("Init");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLblEstadoAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
						.addContainerGap()));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addGap(42, 42, 42).addComponent(jLblEstadoAtual)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Passos",
				javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

		jLblPassos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
		jLblPassos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLblPassos.setText("0");

		javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
		jPanel7.setLayout(jPanel7Layout);
		jPanel7Layout.setHorizontalGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel7Layout
						.createSequentialGroup().addGap(22, 22, 22).addComponent(jLblPassos,
								javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(25, Short.MAX_VALUE)));
		jPanel7Layout.setVerticalGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel7Layout.createSequentialGroup().addGap(43, 43, 43).addComponent(jLblPassos)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
		jPanel8.setLayout(jPanel8Layout);
		jPanel8Layout
				.setHorizontalGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
								.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel8Layout.setVerticalGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGap(1, 1, 1)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap()));

		jTAConsole.setColumns(20);
		jTAConsole.setRows(5);
		jScrollPane1.setViewportView(jTAConsole);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(21, 21, 21)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
						.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jBtnIniciarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBtnIniciarActionPerformed
		if (jTfPalavra.getText() == "") {
			JOptionPane.showMessageDialog(null, "Insira uma palavra!");
		} else {
			// mt.processa(jTfPalavra.getText());
			System.out.println(mt.estadoAtual);

			// while (!end) {

			timer.start();
			System.out.println("time");

			// }

		}

	}// GEN-LAST:event_jBtnIniciarActionPerformed

	private void JbtnResetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_JbtnResetActionPerformed
		boolean end = false;
		timer.stop();
		System.out.println("stop");
		// while (!end) {
		// end = mt.step();
		// }
	}// GEN-LAST:event_JbtnResetActionPerformed

	private void jBtnAbrirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBtnAbrirActionPerformed
		/*
		 * JFileChooser jFCAbrir = new JFileChooser();
		 * 
		 * 
		 * if(jFCAbrir.showOpenDialog(null) == JFileChooser.APPROVE_OPTION){
		 * String path = (jFCAbrir.getSelectedFile().getAbsolutePath()); mt =
		 * new MaquinaDeTuring(path); jTAConsole.setText(jTAConsole.getText() +
		 * "\n" + "Open: " + path);
		 */

		jBtnIniciar.setEnabled(true);
		jBtnPasso.setEnabled(true);

		jTfPalavra.setText("10101");

		// }
		mt = new MaquinaDeTuring(
				"C:/Users/Angélica/git/MaquinaDeTuring/MaquinaDeTuring/src/testes/arquivoPalindromo.txt");
		mt.processa(jTfPalavra.getText());
		delay = (int)jSVelocidade.getValue();
		// System.out.println();

	}// GEN-LAST:event_jBtnAbrirActionPerformed

	private void jBtnPassoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBtnPassoActionPerformed
		if (!end) {
			atualizarFita(mt.getFita());
			end = mt.step();
			jLblEstadoAtual.setText(mt.estadoAtual.getName());
			jTAConsole.setText(jTAConsole.getText() + "\n" + "Passo ");

		} else {
			jBtnPasso.setEnabled(false);
		}

	}// GEN-LAST:event_jBtnPassoActionPerformed

	public void atualizarFita(String str) {
		jLblFitaHead.setText(mt.listaDeCaracteres.get(mt.getCabeca()));
		jLblFitaLeft.setText(mt.getFita().substring(0, mt.getCabeca()));
		jLblFitaRight.setText(mt.getFita().substring(mt.getCabeca() + 1));
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TuringMachineSimulator.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TuringMachineSimulator.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TuringMachineSimulator.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TuringMachineSimulator.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TuringMachineSimulator().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton JbtnReset;
	private javax.swing.JButton jBtnAbrir;
	private javax.swing.JButton jBtnIniciar;
	private javax.swing.JButton jBtnPasso;
	private javax.swing.JCheckBox jCBVelMaxima;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLblEstadoAtual;
	private javax.swing.JLabel jLblFitaHead;
	private javax.swing.JLabel jLblFitaLeft;
	private javax.swing.JLabel jLblFitaRight;
	private javax.swing.JLabel jLblPassos;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JSlider jSVelocidade;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JTextArea jTAConsole;
	private javax.swing.JTextField jTfPalavra;
	// End of variables declaration//GEN-END:variables
}
